inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - config/environments/*
    - config/routes.rb
    - Gemfile
    - Rakefile
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - 'vendor/**/*'
    - config/initializers/**/*
    - db/migrate/**/*
    - app/javascript/**/*
    - node_modules/**/*
    - bin/**/*
    - db/seeds.rb
    - Guardfile
Rails:
  Enabled: true

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# %i, %I以外の書き方も許可
Style/SymbolArray:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

RSpec/ContextWording:
  Enabled: false
  
# Shoulda-matcherを踏襲
RSpec/ImplicitExpect:
  EnforcedStyle: should

# Feature
Capybara/FeatureMethods:
  Exclude:
    - 'spec/features/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'

Metrics/LineLength:
  Max: 85
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  Max: 13
  CountComments: false

# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 45

Metrics/AbcSize:
  Enabled: true
  Max: 20

Style/AndOr:
  EnforcedStyle: conditionals
  
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
