inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - config/environments/*
    - config/routes.rb
    - Gemfile
    - Rakefile
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - spec/support/**/*
    - 'vendor/**/*'
    - config/initializers/**/*
    - db/migrate/**/*
    - app/javascript/**/*
    - node_modules/**/*
    - bin/**/*
    - db/seeds.rb
    - Guardfile
Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# %i, %I以外の書き方も許可
Style/SymbolArray:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

RSpec/ContextWording:
  Enabled: false
  
# Shoulda-matcherを踏襲
RSpec/ImplicitExpect:
  EnforcedStyle: should

# Feature
Capybara/FeatureMethods:
  Exclude:
    - 'spec/features/**/*'
RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'

Metrics/LineLength:
  Max: 85
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - 'spec/features/**/*'

Metrics/MethodLength:
  Max: 15
  CountComments: false

Metrics/BlockLength:
  Max: 45
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: true
  Max: 20

Style/AndOr:
  EnforcedStyle: conditionals

Naming/UncommunicativeBlockParamName:
  Exclude:
    - 'app/views/api/**/*'

Naming/VariableName:
  Exclude:
    - 'app/views/api/**/*'

# 更新時間変更の為に使用しているので…後ほど検討
Rails/SkipsModelValidations:
  Enabled: false

# policieも遅くなりすぎる気がする
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/policies/**/*'
    - 'spec/requests/**/*'
    - 'spec/features/**/*'
