TWITTER_API_KEY: 4igJ8eA3x8ulzhT9B5fj2tQYu
TWITTER_API_SECRET: CNWJVpBOsC3Zrjaet67hfCD0kEH3VcWRQBO4c9BaZuGXOQt1Qk

development:
  TWITTER_ACCESS_TOKEN: '52043701-2evxg41crJk8JGszUvt8RB6oCsaehCNFlgAN5ouix'
  TWITTER_ACCESS_SECRET: '0x5jVJOTcfBBaD5kpeo19oeuKgRnv2x3gKPs197dMHfxX'
  REDIS_HOST: localhost
  REDIS_PORT: 6379

test:
  TWITTER_ACCESS_TOKEN: '52043701-2evxg41crJk8JGszUvt8RB6oCsaehCNFlgAN5ouix'
  TWITTER_ACCESS_SECRET: '0x5jVJOTcfBBaD5kpeo19oeuKgRnv2x3gKPs197dMHfxX'
  REDIS_HOST: localhost
  REDIS_PORT: 6379
