# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: client
  compile: false
  cache_path: tmp/cache/webpacker
  public_output_path: packs

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .jsx
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: true

test:
  <<: *default

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Cache manifest.json for performance
  cache_manifest: true
